### ISSUE TITLE
[Question] are contributions in kotlin welcome?

### ISSUE THREAD

**Issue by ducaale** [romellfudi/VoIpUSSD#15]

**Comment by romellfudi** [comment]
all these days , i tried to convert kotlin but throw me too many errors. so if you want kotlin make new branch 'kotlin'

**Comment by romellfudi** [comment]
Hi @ducaale 
are contributions in kotlin welcome? yes, i build a new branch kotlin, just create a pull request!

**Comment by romellfudi** [comment]
Hi @ducaale , i migrate into kotlin... check the [branch kotlin](https://github.com/romellfudi/VoIpUSSD/tree/kotlin)

**Comment by ducaale** [comment]
instead of maintaining two ussd libraries i think it would be better if you added kotlin support as a module like in https://github.com/florent37/RuntimePermission

**Comment by romellfudi** [comment]
you always can use it(RuntimePermission).
My permission library is NOT into VoidUSSD module, that is the reason everyone could use whatever permission library into 'The App'

**Comment by ducaale** [comment]
HI @romellfudi, no, what i meant is how some library authors structure their library into seperate modules.

**Comment by romellfudi** [comment]
Mmm please an example?:sweat_smile:

**Comment by romellfudi** [comment]
I understand you. But In this project just use one module

**Comment by ducaale** [comment]
Hi @romellfudi, for example in https://github.com/florent37/RuntimePermission they wrote their core library in java and added convenient extensions for kotlin in a separate module so they have:
- runtime-permission (written in java)
- runtime-permission-kotlin (dependent on runtime-permission and written in kotlin)

IMHO i think maintaining the same library in two languages is a bit hard. so my opinion would be to leave the core of VoIpUSSD as it is written in java and add kotlin extensions as needed in a separate module

**Comment by romellfudi** [comment]
@ducaale , thanks a lot. its a great idea... I might do it. HOHO (definitely will do it), I have already learnt kotlin since 3 days. :sweat_smile:
But right now i have not much time. 
Probability next a couple of weeks or months,
if you could help me and just merge the master branch of [KotlinVoipUSSD](https://github.com/romellfudi/KotlinVoIpUSSD)(`usdd-library` module) with this master(VoipUSSD), like:

- ussd-library
- ussd-library-kotlin (rename) or kotlin-ussd-library

Join them, just be carefully with unit tests
Finally made a pull request, i'd appreciate it

**Comment by ducaale** [comment]
ok i will see what i can do

**Comment by romellfudi** [comment]
Hi @ducaale ,  i've done

**Comment by romellfudi** [comment]
Hi @ducaale ,  i've done
