### ISSUE TITLE
Load ussd data without show loading

### ISSUE THREAD

**Issue by Itzmmd** [romellfudi/VoIpUSSD#47]
Hi i was looking for a way to make silent ussd calls i found the google new telephonymanager.sendussdrequest which works fine but it doesn’t support apis lower than 27 is there anyway to make ussd requests without loading in lower apis and read the response even something like creating the whole app in a system overlay

**Comment by romellfudi** [comment]
Hi @Itzmmd, 
I haven't try telephonymanager.sendussdrequest method, .
When i ask Google support they told me that they hadn't thought about any application for user. Nevertheless, nowadays more telcom companies have just introduced ussd transactions in order to help customers requirements.

It's just closed as no an issue, whereas you could keep writing...
