### ISSUE TITLE
Ussd stop at first step

### ISSUE THREAD

**Issue by douala-777** [romellfudi/VoIpUSSD#96]
When I run the app for the first time the process work very good . But when I restart my app the process stop at the first step i don't understand.

**Comment by romellfudi** [comment]
@douala-777 , unfortunately the USSD depends on your TELCOM serve, they build the xml and android parse it to USSD view

**Comment by romellfudi** [comment]
@douala-777 , My recommendation is download the library module and custom the USSSDService class for your flow case.

**Comment by romellfudi** [comment]
@douala-777

**Comment by TechNov** [comment]
@douala-777  I live to be a little long so that you can better understand the concern you have and solve it.
I have been using this library for 2 years, and last week I had to update to Android 11 (library 1.2.f). Suddenly my USSD stopped at the first step on the TECNO Spark8 Smartphiones. however on Samsung and Huawei, it works.
I therefore lost 3 days without result and my client was blocked.
Since yesterday (all night 😂😎) I started to debug the source code of the library (I prefer to integrate the source code instead of the compiled version) and I discovered this morning the following thing:

in `USSDService.java` there is this:
```
private boolean isUSSDWidget(AccessibilityEvent event) {
        Log.d(TAG, event.getClassName().toString());
        return (event.getClassName().equals("amigo.app.AmigoAlertDialog")
                || event.getClassName().equals("android.app.AlertDialog")
                || event.getClassName().equals("com.android.phone.oppo.settings.LocalAlertDialog")
                || event.getClassName().equals("com.zte.mifavor.widget.AlertDialog")
                || event.getClassName().equals("color.support.v7.app.AlertDialog")
               
        );
    }
```

depending on the smartphone brand and version of android, different type of dialog alerts are used and apparently, the Tecno spark 8 used `"com.transsion.widgetslib.dialog.PromptDialog" `while it does not exist in the initial list of the bookstore.
This is how I added `"com.transsion.widgetslib.dialog.PromptDialog"` to the list so that the library can know that `"com.transsion.widgetslib.dialog.PromptDialog"` is the one used by Tecno spark 8 for the USSD.
This solved my problem.
PS: I was able to get the dialog name thanks to this line ( ClassName):  [here](https://github.com/romellfudi/VoIpUSSD/blob/b45395733b31fa0e1f6844eba9d91f420a2dfd2a/ussd-library/src/main/java/com/romellfudi/ussdlibrary /USSDService.java#L45
) 

While those who

**Comment by romellfudi** [comment]
Hello @TechNov, I hope you still great, I am going to create a [PR](https://github.com/romellfudi/VoIpUSSD/pull/98) for your suggestion, thus will merge with main

**Comment by romellfudi** [comment]
@TechNov is ready [release](https://github.com/romellfudi/VoIpUSSD/releases/tag/1.3.0)!!!

**Comment by TechNov** [comment]
@romellfudi  thank's for this great library. i'am African and soon, i will fork your work to adapt it to our locals telecoms operator.

**Comment by romellfudi** [comment]
@douala-777 @TechNov please share my repository and tag me,@romellfudi , in social network and consider donate me. I am the only one who support this project

**Comment by TechNov** [comment]
noted
